# .cpanel.yml
deployment:
  tasks:
    - export DEPLOYPATH=/home/bjmpfehm/p2p-api/
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp passenger.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/touch $DEPLOYPATH/tmp/restart.txt